In [12]:
import pandas as pd
data=pd.read_csv("car data.csv")
df=pd.DataFrame(data)
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

Dummy Column

In [13]:
df.drop(columns="Car_Name",inplace=True)

In [14]:
df

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

,Year,Selling_Price,Present_Price,Kms_Driven,Seller_Type,Transmission,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol
0,2014,3.35,5.59,27000,Dealer,Manual,0,False,True
1,2013,4.75,9.54,43000,Dealer,Manual,0,True,False
2,2017,7.25,9.85,6900,Dealer,Manual,0,False,True
3,2011,2.85,4.15,5200,Dealer,Manual,0,False,True
4,2014,4.60,6.87,42450,Dealer,Manual,0,True,False
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Dealer,Manual,0,True,False
297,2015,4.00,5.90,60000,Dealer,Manual,0,False,True
298,2009,3.35,11.00,87934,Dealer,Manual,0,False,True
299,2017,11.50,12.50,9000,Dealer,Manual,0,True,False
300,2016,5.30,5.90,5464,Dealer,Manual,0,False,True

In [23]:
import pandas as pd

# Read the dataset
df = pd.read_csv("car data.csv")

# Drop Car_Name column
df.drop(columns="Car_Name", inplace=True)

# Create dummy variables for Fuel_Type
df = pd.get_dummies(df, columns=["Fuel_Type"], drop_first=True)

# Create dummy variables for Transmission

df = pd.get_dummies(df, columns=["Transmission"], drop_first=True)

# Display the updated DataFrame
df

,Year,Selling_Price,Present_Price,Kms_Driven,Seller_Type,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Transmission_Manual
0,2014,3.35,5.59,27000,Dealer,0,False,True,True
1,2013,4.75,9.54,43000,Dealer,0,True,False,True
2,2017,7.25,9.85,6900,Dealer,0,False,True,True
3,2011,2.85,4.15,5200,Dealer,0,False,True,True
4,2014,4.60,6.87,42450,Dealer,0,True,False,True
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Dealer,0,True,False,True
297,2015,4.00,5.90,60000,Dealer,0,False,True,True
298,2009,3.35,11.00,87934,Dealer,0,False,True,True
299,2017,11.50,12.50,9000,Dealer,0,True,False,True
300,2016,5.30,5.90,5464,Dealer,0,False,True,True

In [24]:
import pandas as pd

# Read the dataset
df = pd.read_csv("car data.csv")

# Drop Car_Name column
df.drop(columns="Car_Name", inplace=True)

# Create dummy variables for Fuel_Type
df = pd.get_dummies(df, columns=["Fuel_Type"], drop_first=True)

# Create dummy variables for Transmission

df = pd.get_dummies(df, columns=["Transmission"], drop_first=True)

# Create dummy variables for Seller_Type
df = pd.get_dummies(df, columns=["Seller_Type"], drop_first=True)


# Display the updated DataFrame
df

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Transmission_Manual,Seller_Type_Individual
0,2014,3.35,5.59,27000,0,False,True,True,False
1,2013,4.75,9.54,43000,0,True,False,True,False
2,2017,7.25,9.85,6900,0,False,True,True,False
3,2011,2.85,4.15,5200,0,False,True,True,False
4,2014,4.60,6.87,42450,0,True,False,True,False
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,0,True,False,True,False
297,2015,4.00,5.90,60000,0,False,True,True,False
298,2009,3.35,11.00,87934,0,False,True,True,False
299,2017,11.50,12.50,9000,0,True,False,True,False
300,2016,5.30,5.90,5464,0,False,True,True,False

Where Function

In [28]:
import numpy as np
df=pd.DataFrame({"Marks":[40,35,65,31,70,95,18]})
df["Result"]=np.where(df["Marks"]>40,"pass","Fail")
df

   Marks Result
0     40   Fail
1     35   Fail
2     65   pass
3     31   Fail
4     70   pass
5     95   pass
6     18   Fail

In [30]:
df["Grade"]=np.where(df["Marks"]>75,"A",np.where(df["Marks"]>50,"B","C"))
df

   Marks Result Grade
0     40   Fail     C
1     35   Fail     C
2     65   pass     B
3     31   Fail     C
4     70   pass     B
5     95   pass     A
6     18   Fail     C

Arithmatic OR Mathmatical Oparater

In [32]:
df=pd.DataFrame({
    "Math":[45,60,75],
    "Science":[50,60,70]
})
df["Total"]=df["Math"]+df["Science"]
df["Average"]=df["Total"]/2
df

   Math  Science  Total  Average
0    45       50     95     47.5
1    60       60    120     60.0
2    75       70    145     72.5

Test,Train,Split

In [55]:
import pandas as pd
df = pd.read_csv("car data.csv")
df
#dependent hoy e y ma jay
# dependent=y

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [38]:
df.drop(columns="Car_Name",inplace=True)

In [39]:
df

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [40]:
df=pd.get_dummies(df,drop_first=True)
# jo kai pan parameter na aapiye to badhi je numeric format na hoy tene convert karshe...

In [41]:
df

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,2014,3.35,5.59,27000,0,False,True,False,True
1,2013,4.75,9.54,43000,0,True,False,False,True
2,2017,7.25,9.85,6900,0,False,True,False,True
3,2011,2.85,4.15,5200,0,False,True,False,True
4,2014,4.60,6.87,42450,0,True,False,False,True
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,0,True,False,False,True
297,2015,4.00,5.90,60000,0,False,True,False,True
298,2009,3.35,11.00,87934,0,False,True,False,True
299,2017,11.50,12.50,9000,0,True,False,False,True
300,2016,5.30,5.90,5464,0,False,True,False,True

In [56]:
Y=df["Selling_Price"]
print(Y)
X=df.drop(columns=["Selling_Price"])
print(X)

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64
    Car_Name  Year  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0       ritz  2014           5.59       27000    Petrol      Dealer
1        sx4  2013           9.54       43000    Diesel      Dealer
2       ciaz  2017           9.85        6900    Petrol      Dealer
3    wagon r  2011           4.15        5200    Petrol      Dealer
4      swift  2014           6.87       42450    Diesel      Dealer
..       ...   ...            ...         ...       ...         ...
296     city  2016          11.60       33988    Diesel      Dealer
297     brio  2015           5.90       60000    Petrol      Dealer
298     city  2009          11.00       87934    Petrol      Dealer
299     city  2017          12.50        9000    Diesel      Dealer
300     brio  2016           5.90        5464    Petrol      Dealer

    Transmission  Owner
0         Manual      0
1         Manual      0
2         Manual      0
3         Manual      0
4         Manual      0
..           ...    ...
296       Manual      0
297       Manual      0
298       Manual      0
299       Manual      0
300       Manual      0

[301 rows x 8 columns]

In [61]:
print("x=",X.shape)
print("Y=",Y.shape)#dependent

x= (301, 8)
Y= (301,)

In [64]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [65]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(240, 8)
(61, 8)
(240,)
(61,)

1. Find the total units produced by each product_category.
2. Calculate the average profit for each factory.
3. Find the total defective_units for each shift.
4. Calculate the average production_time_hr for each supervisor.
5. Find the total energy_consumption_kwh for each factory and shift.
6. For each product_category, calculate:
total units_produced
average profit
maximum defective_units.
7. For each factory, calculate:
mean production_time_hr
median machine_downtime_hr.
8. For each shift, compute:
minimum profit
maximum profit
average units_produced.
9. For each supervisor, calculate:
total units_produced
total defective_units.
10. Using apply(), calculate the defect rate for each row:
defect_rate=defective_units/units_produced
11. Using groupby().apply(), find the profit range (max − min) for each factory.
12. Using groupby().apply(), find the row with maximum units_produced in each product_category.
13. Use apply() to create a new column efficiency_score:
efficiency=units_produced/production_time_hr
14. Find how many times each product_category appears in the dataset.
15. Count the number of records for each shift.
16. Find the most frequent supervisor using value_counts().
17. Sort the dataset by profit in descending order.
18. Sort the dataset by:
	product_category ascending
units_produced descending

In [66]:
df=pd.read_csv("production_analysis_dataset.csv")
df

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209

In [67]:
df.groupby("product_category")["units_produced"].sum()

product_category
Automotive     9408
Electronics    7491
Furniture      7251
Name: units_produced, dtype: int64

In [68]:
df.groupby("factory")["profit"].mean()

KeyError: 'factoey'