1-D  =>Series
0 thi numbring Start thay...

In [13]:
import pandas as pd 
import numpy as np
marks=[85,90,58,69,81,52]
s=pd.Series(marks)
print(s)

0    85
1    90
2    58
3    69
4    81
5    52
dtype: int64

In [3]:
import pandas as pd 
marks=[85,90,58,69,81,52]
s=pd.Series(marks,index=["A","B","C","D","E","F"])
print(s)

A    85
B    90
C    58
D    69
E    81
F    52
dtype: int64

create series by using tuple

In [5]:
data=("a","b","c")
s=pd.Series(data)
s

0    a
1    b
2    c
dtype: object

create series by using dictionary

usiing 2d data

In [7]:
data={"Name":["Alice","Bob","Charlie"],"Age":[25,30,35],"City":["New York","Los Angeles","Chicago"]}
s1=pd.Series(data)
print(s1)

Name               [Alice, Bob, Charlie]
Age                         [25, 30, 35]
City    [New York, Los Angeles, Chicago]
dtype: object

In [9]:
data={"name":"A",
        "age":25,
        "city":"New York"   
         }
s2=pd.Series(data)
print(s2)

name           A
age           25
city    New York
dtype: object

In [11]:
dict={"a":20,"b":10,"c":30}
s3=pd.Series(dict)
s3

a    20
b    10
c    30
dtype: int64

In [14]:
a=np.array([1,2,3,4,5])
s=pd.Series(a)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

crete series by using array

2-D DataFrame

In [17]:
data={"Name":["Alice","Bob","Charlie","David"],
"Age":[25,30,35,40],
"City":["New York","Los Angeles","Chicago","UK"],
"employee":[45000,50000,97000,65000],
"position":["Intern","Devloper","HR","CXO"]}
df=pd.DataFrame(data)
df

      Name  Age         City  employee  position
0    Alice   25     New York     45000    Intern
1      Bob   30  Los Angeles     50000  Devloper
2  Charlie   35      Chicago     97000        HR
3    David   40           UK     65000       CXO

Create DataFrame by using List

In [20]:
data=[["a",80],["B",90],["C",100]]
df=pd.DataFrame(data,columns=["Name","Marks"],index=["10","20","30"])
df

   Name  Marks
10    a     80
20    B     90
30    C    100

Crete dictionary by Using Pandas Series

In [27]:
s1=pd.Series([1,2,3])
s2=pd.Series([8,9,10])
df=pd.DataFrame({"col1":s1,"Col2":s2})
df

   col1  Col2
0     1     8
1     2     9
2     3    10

How to Read csv File|

In [34]:
df=pd.read_csv("matches.csv")
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

Loc function

In [39]:
df.loc[3:10]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
6,7,2017,Mumbai,2017-04-09,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
7,8,2017,Indore,2017-04-10,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
9,10,2017,Mumbai,2017-04-12,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
10,11,2017,Kolkata,2017-04-13,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,8,SP Narine,Eden Gardens,A Deshmukh,NJ Llong,NaN

In [40]:
df.loc[3:10,["id","city","date"]]

    id       city        date
3    4     Indore  2017-04-08
4    5  Bangalore  2017-04-08
5    6  Hyderabad  2017-04-09
6    7     Mumbai  2017-04-09
7    8     Indore  2017-04-10
8    9       Pune  2017-04-11
9   10     Mumbai  2017-04-12
10  11    Kolkata  2017-04-13

In [41]:
# column fatch karva mate...
df[["team1","team2","toss_winner"]]

,team1,team2,toss_winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore
...,...,...,...
631,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore
632,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore
633,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders
634,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
635,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad

iloc function

in this function (end-1) fundamental are working

In [42]:
df.iloc[3:9,4:6]
# df.iloc[row,column]

                         team1                   team2
3       Rising Pune Supergiant         Kings XI Punjab
4  Royal Challengers Bangalore        Delhi Daredevils
5                Gujarat Lions     Sunrisers Hyderabad
6        Kolkata Knight Riders          Mumbai Indians
7  Royal Challengers Bangalore         Kings XI Punjab
8             Delhi Daredevils  Rising Pune Supergiant

How to convert DataFrame into csv file

In [43]:
data={"Name":["Alice","Bob","Charlie","David"],
"Age":[25,30,35,40],
"City":["New York","Los Angeles","Chicago","UK"],
"employee":[45000,50000,97000,65000],
"position":["Intern","Devloper","HR","CXO"]}
df=pd.DataFrame(data)
df

      Name  Age         City  employee  position
0    Alice   25     New York     45000    Intern
1      Bob   30  Los Angeles     50000  Devloper
2  Charlie   35      Chicago     97000        HR
3    David   40           UK     65000       CXO

In [46]:
df.to_csv("a.txt")

In [ ]:
df.describe()
#  describe ne statistical data pan kahe che...

             Age     employee
count   4.000000      4.00000
mean   32.500000  64250.00000
std     6.454972  23428.97067
min    25.000000  45000.00000
25%    28.750000  48750.00000
50%    32.500000  57500.00000
75%    36.250000  73000.00000
max    40.000000  97000.00000

In [ ]:
df.info()
#  it will be give all information about daata

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      4 non-null      object
 1   Age       4 non-null      int64
 2   City      4 non-null      object
 3   employee  4 non-null      int64
 4   position  4 non-null      object
dtypes: int64(2), object(3)
memory usage: 292.0+ bytes